# Generated by Django 5.0.6 on 2024-05-15 04:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_threshold', models.FloatField()),
                ('rainfall_threshold', models.FloatField()),
                ('comparison_operator', models.CharField(choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('==', '==')], max_length=2)),
                ('frequency', models.DurationField(choices=[(datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(days=30), 'Monthly'), (datetime.timedelta(days=365), 'Yearly')])),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('next_check', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weather_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weathercondition')),
            ],
        ),
    ]
