# Generated by Django 5.0.6 on 2024-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercondition',
            name='frequency',
            field=models.DurationField(choices=[(86400.0, 'Daily'), (2592000.0, 'Monthly'), (31536000.0, 'Yearly')]),
        ),
    ]
