# Generated by Django 5.0.6 on 2024-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathercondition_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercondition',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10),
        ),
    ]
